jc/cli.py
Arguments can appear like so: `-*`, `--*`, or `*`. Since we pop all args that match `-*` and return if `--*` exists, all that is left is keywords that match `*` - if these are not present, then the only thing that was in args_given was options, and so we should return.
=> Handle case where only options are passed.

jc/parsers/history.py
Instead of doing two passes over the data in process(), it is possible to do one pass, which makes the code a lot simpler - using .isdigit() also helps avoid additional exception checks.
In parse(), we don't use cleandata anywhere else, so we don't need to allocate a list, since filter() is iterable. This helps avoid a list allocation, and if all strings are empty, we will not enter the loop for filter - for instance:
```
a = ["", '', "", "hello"]
for word in filter(None, a):
print(word)
>>> hello
```
You can iterate over the filter directly for almost every parser, which would help simplify and speed the code up since you would avoid a list allocation each time.
=> Simplify process() in history.py, avoid list allocation in parse()

jc/cli.py, tests/test_cli.py
We only care about the command when testing magic() - by moving that out, we can easily test the command. I created a generate_magic_command() function, which returns a boolean and a command - the boolean signifies a valid command, and the command is a command or None if no command could be generated.
I also made some small tweaks (removed a list() call, fixed a possible bug with no arguments., moved magic_dict instantiation past the fast path checks to avoid making a dict if not needed.) This also includes two tests for the commands that didn't function correctly.
=> Move core magic() logic into seperate function for testability, minor tweaks

README.md, jc/cli.py, requirements.txt, setup.py
Hello, I'd like to propose a feature for custom (local) parsers. Benefits:
* Lower the barrier for entry to write new parsers
* Allow override of builtin parsers for strange systems or command-line arguments
* Allow use of jc with uncommon or specialized apps (for which upstream submission would not be appropriate)
This PR includes such a feature and will include parsers present in `.py`
files placed into the `jc/jcparsers` folder of a user's app-data directory.
Determining an appropriate app-data directory for the current OS did
require a new dependency on the "appdirs" package.
I have tested the changes on Linux. I don't have a Windows or Mac available
to test or verify the path locations I documented, but these paths seem to
be correct judging from the appdirs documentation. Aside from …
=> Load custom parsers from <user_data_dir>/jc/jcparsers

jc/cli.py, setup.py
Tested/works on pygments 2.3.1, this backward support may help your Debian request for packaging since it makes you independent of a pygments update.
Feel free to reject this request if you don't want the legacy baggage.
=> Support older pygments

jc/parsers/iw_scan.py
Ref https://github.com/kellyjonbrazil/jc/issues/94#issuecomment-755162509
This improves the detections of lines that start with space chars in the iw_scan parser.
Without this one only gets the `mac_address` and `interface` fields on Arch Linux and Termux.
=> iw_scan: Improve detection of lines starting with spaces

jc/parsers/update_alt_q.py
Update the `update-alternatives --query` parser as discussed in [this thread](https://github.com/kellyjonbrazil/jc/issues/230) so the JSON is a closer match for the `update-alternatives --query` plain text output.
=> Update name of alternative from name to alternative

jc/parsers/id.py, tests/test_id.py
If a group does not exist only gid is present in the command output.
=> id: parse output without name

CHANGELOG, jc/lib.py, jc/parsers/url.py, man/jc.1, setup.py, tests/test_url.py
- Fix URL string parser path list for URLs ending in a forward slash
=> fix url parser for urls ending in slash

CHANGELOG, docs/parsers/ip_address.md, jc/lib.py, jc/parsers/ip_address.py, man/jc.1, setup.py
- Fix IP Address string parser for older python versions that don't cleanly accept decimal input format - IPv6 fix (e.g. python 3.6)
=> fix for ipv6 ip-address parser with older python and version bump

jc/parsers/id.py, tests/test_id.py
id parser did not work correctly if space is present in user or group
name.
=> id: support space in names

jc/parsers/xrandr.py, tests/fixtures/generic/xrandr_simple.json, tests/test_xrandr.py
Currently the reflect value of a device is included in the rotation key as a combination of both rotation and reflection (e.g. normal X axis). With this modification we move the reflection value to its own key in the JSON document like so:
```json
{
...
"rotation": "...",
"reflection": "...,
...
}
```
Fixes: issue #360
=> Move the reflect value in its own key (xrandr) #360

jc/parsers/proc.py
Zombie processes don't have the umask field available.
=> Make umask optional in /proc/PID/status

EXAMPLES.md, README.md, jc/lib.py, jc/parsers/x509_csr.py
A Certificate Request (CSR) parser has been introduced based on X.509 certificate parser.
=> Adding certificate request parser

jc/parsers/bluetoothctl.py, tests/fixtures/generic/bluetoothctl_device_random.out, tests/test_bluetoothctl.py
The bluetoothctl device parser is implemented so that it aborts the parsing process immediately returning what it has collected so far. This is because the parser should work in hydrid way to support outputs comming from bluetoothctl devices and bluetoothctl info calls.
=> Parse appearance and modalias lines for mouse devices (fixes #419)

docs/lib.md, jc/__init__.py, jc/cli.py, jc/lib.py
extract to public `jc.get_parser(parser_name)`
still now it is only possible to do a:
```python
for data in data_list:
jc.parse(parser_name, data, quiet=True),
```
with `get_parser` this is possible:
```python
my_parser = jc.get_parser(parser_name)
for data in data_list:
my_parser.parse(data, quiet=True),
```
TODO:
=> extract to public jc.get_parser(parser_name)

docs/parsers/crontab.md, jc/parsers/crontab.py
fix: 
- crontab parser: remove double entry in doc
=> fix: crontab remove double entry in doc

tests/fixtures/create_fixtures.sh, tests/fixtures/opensuse-leap-15.5/efibootmgr-v.json, tests/fixtures/opensuse-leap-15.5/efibootmgr-v.out, tests/fixtures/opensuse-leap-15.5/efibootmgr.json, tests/fixtures/opensuse-leap-15.5/efibootmgr.out, tests/test_efibootmgr.py
add efibootmgr output test case without -v parameter.
Now we have both `sudo efibootmgr` and `sudo efibootmgr -v` test cases.
=> add "sudo efibootmgr" (without -v) output test case

jc/parsers/bluetoothctl.py, tests/fixtures/generic/bluetoothctl_controller_with_manufacturer.out, tests/test_bluetoothctl.py
This commit fixes the controller parser scheme in order to take care and extract some extra attributes, the manufacturer and version. The order of the attributes appearing in the regexp scheme must follow the order they appear in the `bluetoothctl show` outputs.
A new test has been added to test outputs with these extra attrs.
Fixes #598
=> Fix broken controller regexp scheme in the bluetoothctl parser

.github/workflows/pythonapp.yml
Updated the `pythonapp.yml` workflow to trigger only on non-draft pull requests, ensuring workflows run only when a PR is ready for review or merging.
=> fix: Edit pythonapp.yml workflow to run on non-draft PRs

runtests.sh
This PR enables timezone-specific testing by using the TZ environment variable. Tests can now run in Los Angeles timezone without changing the system timezone, ensuring isolated and reproducible results.
This change was tested successfully on multiple macOS and Linux machines for compatibility.
Note: The `TZ` environment variable is ignored on Windows systems.
=> Timezone Testing with TZ Env Variable

jc/parsers/pyedid/edid.py, jc/parsers/pyedid/helpers/edid_helper.py
`typing.ByteString` has been removed:
https://docs.python.org/3.14/whatsnew/3.14.html
The modernizing guide suggests `collections.abc.ByteString` which has also been removed; the recommendation is to use either:
- just `bytes`
- `collections.abc.Buffer`
- a union of `bytes`, `bytesarray`, etc.
https://typing.readthedocs.io/en/latest/guides/modernizing.html#modernizing-byte-string
https://docs.python.org/3/library/collections.abc.html#collections.abc.ByteString suggests `bytes | bytesarray` so I'm going with that here.
=> Adjust for removal of typing.ByteString in Python 3.14
